language: go
matrix:
  include:
  - go: 1.8.3
before_install:
- openssl aes-256-cbc -K $encrypted_e64c418b6cf2_key -iv $encrypted_e64c418b6cf2_iv -in .travis/github_deploy_key.enc -out ./travis/github_deploy_key -d
- mkdir -p "${GOPATH}/bin"
- go get github.com/Masterminds/glide
install:
- make install
after_success:
- |2
  $(npm bin)/set-up-ssh --key "$encrypted_XXXXXXXXXXXX_key" \
                        --iv "$encrypted_XXXXXXXXXXXX_iv" \
                        --path-encrypted-key ".travis/github_deploy_key.enc"
before_deploy:
- make release
deploy:
  provider: releases
  file:
  - release/linux_amd64/healthy
  - release/linux_386/healthy
  - release/darwin_amd64/healthy
  - release/darwin_386/healthy
  - release/freebsd_386/healthy
  - release/freebsd_amd64/healthy
  - release/windows_amd64/healthy.exe
  - release/windows_386/healthy.exe
  skip_cleanup: true
  on:
    tags: false
    repo: WianVos/healthy
GH_USER_EMAIL=wianvos@gmail:
  com:
    secure: IN+EML93Ra6Kh2ajWKtEKAhvgdqZphyvvoxmsezO4I6fB1EbP3PmRZKmaG6LLLG6R2Mu9z4DOxVgGNvLUVs/BTdpWD89EgcKa67h1upq+IuyfEedWPY+MWPLijBd3rQirtPJA1AjCe2pwNx0Sw0zobY2rsuiKVZJkuvmdYIQqJF9gLyWcfCHYaVQnWUInIM17uByJZkPB2HZaxjS0y2KzbsX9NVRpjvnhsidBSBB13PTdA1IgA7GsvWEJ+wDLxuEE9L+ftPaAGgEfjAvp+1aboDEtZudBjwfF9QhJ8IXLoSZX6msbh3auVD3wzLIDvKnvYTXZQjICcBf5xHX7z1FjZKfBVcJbGeH/bssOvvOy8d6UW7zE4bcViM6LUW5azTzuSb8Ak2FD86Pg83c1JtKaHaOVrYA7nuGgOKstp+FH0Rv/lFUJk2y+SQZbgFuxCwLJIb51SvyFmcmwRK0mfXfmLF3zd8AmX08lKxfZuBMxCRjz8WmtZhUWxgnYHgLAeFJlFPAmFzSh1rRTXS841sp8BMLIfkEqMHA6TUL9rA3+Eje5ZnKI/MAIR67BANZcoKbrDXi8oXFhu46rjp2HVbwWebbqjz4cUj2STlC4I3n3QSnb5KXI3n8o7fgAjV88s4/kpnSvW8iHsy40b0btClT1TUYGmcsHoxPmdThHmiEti0=
