language: go
matrix:
  include:
  - go: 1.8
install:
- make install
before_deploy:
- make release
deploy:
  provider: releases
  api_key:
    secure: "dBHgEC2MWwEoE/wjTJQww3gboAv06OkfAovA4W0U0Sj6i2iHQYf2Yg8wHpH9F4HZYS+6bTT5aX7BKJFG9fHiPZ7Nr5wh72AvlfSrhZ63cAVW6CXoHxSEggv4wv3+f+YZ76zOwIUG2uRfM1qzZGGpF8RBAfr50peoW5dasULW98EiVauZ1l7CIC6Da6bcRiI/KuXkaLvmkRldVfbaLyH2F8TSxMmcQ1ax8BsuVqIV9ALWP5cGIJrKLXe6HAyBPXgY9tBHagigGgMZJsTAntpthbAx4CyLD+CYcNtsz8cr8qnnrUsNROlrHsuWw0fdiNrhAxbdVsGvs5hkN9bwU/I2veZQDkim1PVpxyGv8ru7yBgYg5VJFimDhxao8SHaIrBXAK1SY8MeKFt4nP571PiGn5bVCUHabYJDK8eo37UYqytVXxZGtO7oEingVZyOdpKKE52LnH+1GJNL9DpFRTscZpDGDwJSsOLATF1RPEFeSpXzAlth9fqvjTKQW4E4jdXazrr16xKnSsiYGEsAG6NkDrd/c0Wvi08JTotMak6YmWyvkkLOH8Deku/Oe2nUciS9yGG4rlSq8MyyUSTktZ5HExj27AocdCUUVwxwc27xoPAUjwVGqR9guuMNu6D1pCKyS9w9VPP1khbRY4TRKv2sZ1yEt+1PRSe6neMOkLsmE64="
  file:
  - release/healthy
  skip_cleanup: true
  on:
    tags: true
    repo: WianVos/healthy

